### ISSUE TITLE
php_forbidden_function.yml probably shouldn't be committed

### ISSUE THREAD

**Issue by dkisselev** [nilportugues/php_forbidden_functions#1]
As a user, if I try to modify it, I won't be able to checkout a newer release of your library because the changes would conflict/be overwritten.

A better solution is might be to add some install instructions asking users to copy the sample to .yml, or maybe a composer post-install script that copies the file for users.

**Comment by nilportugues** [comment]
Instructions are in the README.md

I added the `php_forbidden_function.yml` file to the `.gitignore` file for release 1.0.3
