### ISSUE TITLE
Unit tests errors on Travis CI during pull request

### ISSUE THREAD

**Issue by michelezamuner** [nilportugues/php_forbidden_functions#5]
I made a pull request, but Travis CI is failing while running unit tests:

```
The command "php vendor/phpunit/phpunit/phpunit tests/" exited with 1.
```

How can I see what tests are being run, and where they are failing?

**Comment by nilportugues** [comment]
Oh! That's because you're missing `composer require --dev phpunit/phpunit` 

This library had no tests ^^;

**Comment by nilportugues** [comment]
I'll fix this for the next release :+1:

**Comment by michelezamuner** [comment]
Ok, great!
